.TH cdate 1 "November 2011" Linux "User Manuals"
.SH NAME
cdate \- show Chinese lunisolar date,顯示中國傳統農曆日期
.SH SYNOPSIS
.B cdate [-h] [-d
.I date
.B ] [-a] [-g] [-n] [-z] [
.I date
.B ]
.SH DESCRIPTION
\fIcdate\fR顯示中國傳統農曆日期，默認顯示當天的農曆年月日或當前的年月日時四
柱。也可以指定 1901 - 2050 年之間的日期。
.SH "OPTIONS"
.IP "\fB\-d \fIdate\fR\fR"
使用指定的年月日時 \fIdate\fR.
.IP "\fB\-a\fR"
顯示所有項目。
.IP "\fB\-g\fR"
顯示公曆年月日及星期。
.IP "\fB\-n\fR"
不顯示農曆年月日及節氣、節日。
.IP "\fB\-z\fR"
顯示四柱。
.IP "\fB\-h\fR"
顯示幫助。
.SH "PARAMETERS"
指定的\fIdate\fR格式必須爲 YYYYMMDDHH，且年份在 1901 與 2050 年之間，
如 2050010101 。
.SH "REPORTING BUGS"
Send bug reports and/or suggestions to vinoca <supoingo@163.com>.
.SH "COPYING"
Licensed under the BSD license.
.SH "SEE ALSO"
.BR date (1)
